# Reversible Crafting Plugin Config
############################################################################
#                                                                          #
#                          ReversibleCrafting                              #
#                                                                          #
# Made by: ArthropodR                                                      #
# Bug Reports: https://github.com/ArthropodR/ReversibleCrafting/issues     #
# Source Code: https://github.com/ArthropodR/ReversibleCrafting            #
#                                                                          #
############################################################################